{{- if .Values.dip.enabled -}}
{{ if .Values.dip.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nimbit-cloud.dip.fullname" . }}
  labels:
    nimbit.cloud/environment: {{ include "nimbit-cloud.deployment.environment" . }}
    nimbit.cloud/tenant-type: {{ include "nimbit-cloud.tenant.type" . }}
    nimbit.cloud/tenant-name: {{ include "nimbit-cloud.tenant.name" . }}
    {{- include "nimbit-cloud.dip.labels" . | nindent 4 }}
  {{- with .Values.dip.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dip.service.type }}
  ports:
    - port: {{ .Values.dip.service.port }}
      targetPort: {{ .Values.dip.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nimbit-cloud.dip.selectorLabels"  . | nindent 4 }}
  {{- end -}}
  {{- end -}}