{{-  if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "javaapp.fullname" . }}
  labels:
    {{- include "javaapp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "javaapp.selectorLabels" . | nindent 4 }}
  {{- end -}}    