apiVersion: v1
entries:
  apps:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2022-12-12T12:46:29.5655844+01:00"
    description: Apps of apps
    digest: 711bc90b26bedfcf33c0ce00c8d95e3607b9a8245fb7ad15631ca18eb8e60b55
    name: apps
    type: application
    urls:
    - app-of-apps/apps-0.1.0.tgz
    version: 0.1.0
  cp-kafka-connect:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-12-12T12:46:29.5671744+01:00"
    description: A Helm chart for Confluent Kafka Connect on Kubernetes
    digest: c16a0c25990ef55c77361bb5c1d6423f8176e553ca73da6479eb7edd520c1144
    name: cp-kafka-connect
    urls:
    - cp-kafka-connect/cp-kafka-connect-0.1.0.tgz
    version: 0.1.0
  cp-kafka-rest:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-12-12T12:46:29.5682269+01:00"
    description: A Helm chart for Confluent Kafka REST Proxy on Kubernetes
    digest: f58c0525b336cdabb6ab1fbe8d252e74658f3683a52c39fd55790a81cafaf812
    name: cp-kafka-rest
    urls:
    - cp-kafka-rest/cp-kafka-rest-0.1.0.tgz
    version: 0.1.0
  cp-ksql-server:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-12-12T12:46:29.5695304+01:00"
    description: A Helm chart for Confluent KSQL Server on Kubernetes
    digest: 87332eee9452e6fc35fc1d5cd3ba071a7cfcaa9cb4fa70514b69196537c57f83
    name: cp-ksql-server
    urls:
    - cp-ksql-server/cp-ksql-server-0.1.0.tgz
    version: 0.1.0
  grafana:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-12-12T12:46:29.5779891+01:00"
    description: A Helm chart for Kubernetes
    digest: 212418b047dbcd18bf9ac148723d37ca994aabf09c514d137f83166be988675d
    name: grafana
    type: application
    urls:
    - grafana-plus/grafana-0.1.0.tgz
    version: 0.1.0
  javaapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-12-12T12:46:29.5804541+01:00"
    description: A Helm chart for Kubernetes
    digest: 62b0e46ccd347c32b42e86ef22d33b6f9fa2cb977168c481c0edb8f1feef5b2d
    name: javaapp
    type: application
    urls:
    - java/javaapp-0.1.0.tgz
    version: 0.1.0
  node:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-12-12T12:46:29.5814424+01:00"
    description: A nimbit Helm chart for node applications
    digest: c36371f03835f9071cc61ce094c0fc1739550be8e3c9318d19889359cba20ff9
    name: node
    urls:
    - node-app/node-0.0.1.tgz
    version: 0.0.1
generated: "2022-12-12T12:46:29.5644975+01:00"
