{{- if .Values.breeze.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nimbit-cloud.breeze.serviceAccountName" . }}
  labels:
    nimbit.cloud/environment: {{ include "nimbit-cloud.deployment.environment" . }}
    nimbit.cloud/tenant-type: {{ include "nimbit-cloud.tenant.type" . }}
    nimbit.cloud/tenant-name: {{ include "nimbit-cloud.tenant.name" . }}
    {{- include "nimbit-cloud.breeze.labels" . | nindent 4 }}
  {{- with .Values.breeze.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
