{{- range $app := .Values.argocdApplications -}}
---
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ $.Values.global.env }}
  namespace:  {{ default $.Values.global.namespace .argocd.namespace }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $value.name  }} : {{ $value.value | quote }}
    {{- end }}
spec:
  project: {{ $.Values.global.spec.project }}
  source:
    plugin: 
      {{ toYaml .plugin }} 
    repoURL:  {{ default $.Values.global.spec.source.repoURL .repoURL | squote }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision | squote }}
    {{- if .helm.chart }}
    chart: {{ .helm.chart | squote }}
    {{- end }}
    path: {{ .path | squote }}
    {{- if default $.Values.global.helmDefault .helm.enabled }}
    {{- if .helm.parameters }}
    helm:
      passCredentials: true
      parameters:
        {{- range $key, $value := .helm.parameters }}
        - name: {{ $value.name  | quote }}
          value: {{ $value.value | quote }}
        {{- end }}
    {{- else }}   
    helm:
      passCredentials: true
      valueFiles:
        
    {{- end }}

    {{- end }}
  destination:
    namespace: {{ default $.Values.global.spec.destination.namespace  .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
{{- end }}