{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }} 
spec:
  secretName: {{ .Values.certificate.secret }} 
  issuerRef:
    kind: {{ .Values.certificate.issuer.kind }} 
    name: {{ .Values.certificate.issuer.name }} 
  commonName: {{ .Values.certificate.commonName }}  
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    {{ print "- " (. | quote) }}
    {{- end }}
  {{- end }}
