{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.global.certificate.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuer }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - "{{ . }}"
    {{- end }}
{{- end }}
